version: '3.4'

services:
  sentinel:
    image: weithenn/redis-sentinel:latest
    ports:
      - "26379:26379"
    volumes:
      - /proc:/wproc
    networks:
      - vnet
    deploy:
      replicas: 3
      update_config:
        delay: 60s

networks:
  vnet:
